// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp-JaM7WT9XXT5oUcKK0RDPzpn6FUxoSE',
    appId: '1:445894480792:web:92f82a63dc178e2b9cd1ed',
    messagingSenderId: '445894480792',
    projectId: 'lumocare',
    authDomain: 'lumocare.firebaseapp.com',
    storageBucket: 'lumocare.firebasestorage.app',
    measurementId: 'G-BTE0R2TY9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq83Vl2ArlyJuj1uBq94eklcVV_iTqzQ0',
    appId: '1:445894480792:android:32c6a7de9376d0719cd1ed',
    messagingSenderId: '445894480792',
    projectId: 'lumocare',
    storageBucket: 'lumocare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVoMmnwi1jSdagKhDJfIEr1HHnOOQPNOE',
    appId: '1:445894480792:ios:85790af650aff8029cd1ed',
    messagingSenderId: '445894480792',
    projectId: 'lumocare',
    storageBucket: 'lumocare.firebasestorage.app',
    iosBundleId: 'com.example.mealselection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVoMmnwi1jSdagKhDJfIEr1HHnOOQPNOE',
    appId: '1:445894480792:ios:85790af650aff8029cd1ed',
    messagingSenderId: '445894480792',
    projectId: 'lumocare',
    storageBucket: 'lumocare.firebasestorage.app',
    iosBundleId: 'com.example.mealselection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp-JaM7WT9XXT5oUcKK0RDPzpn6FUxoSE',
    appId: '1:445894480792:web:ad30307bd4f015519cd1ed',
    messagingSenderId: '445894480792',
    projectId: 'lumocare',
    authDomain: 'lumocare.firebaseapp.com',
    storageBucket: 'lumocare.firebasestorage.app',
    measurementId: 'G-84F1SG6PEW',
  );

}